### ISSUE TITLE
problem with cogs

### ISSUE THREAD

**Issue by Kejlo523** [MrSpaar/discord-bot#3]
Os: Ubuntu 20.
python3 bot.py
Traceback (most recent call last):
  File "/home/kejlo/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 601, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kejlo/Pulpit/music/cogs/music.py", line 38
    return {'embed': embed, 'source': info['formats'][0]['url'], 'title': info['title']}
                                                                                       ^
IndentationError: unindent does not match any outer indentation level

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 15, in <module>
    bot.load_extension(extension)
  File "/home/kejlo/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 658, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/kejlo/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 604, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.music' raised an error: IndentationError: unindent does not match any outer indentation level (music.py, line 38)

**Comment by MrSpaar** [comment]
The problem should be solved now, there was an extra space ^^'
